language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.11"

script: make test-all SKIP_PHANTOMJS_TEST=1

matrix:
  allow_failures:
    - node_js: "0.11"

# We want to be notified when something happens.
notifications:
  irc:
    channels:
      - "irc.freenode.org#jsx"
    on_success: always # [always|never|change] # default: change
    on_failure: always # [always|never|change] # default: always
